# Generated by Django 5.2.8 on 2026-02-02 16:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Maximum amount to spend in this category.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='budget amount')),
                ('period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], help_text='Time period for the budget (WEEKLY or MONTHLY).', max_length=7, verbose_name='budget period')),
                ('start_date', models.DateField(help_text='Budget start date.', verbose_name='start date')),
                ('end_date', models.DateField(help_text='Budget end date.', verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'ordering': ['-start_date', 'category__name'],
            },
        ),
    ]
